import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';

const Button = styled.button`
  color: white;
  background: blue;
`;

const ProjectWrapper = styled.section`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(25rem, 1fr));
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joyanna's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProjectWrapper>
          <figure>
            <img
              src="https://res.cloudinary.com/labofthingsimages/image/upload/v1670295127/Portfolio_Images/buttercups3_de6mky.png"
              alt="Buttercups"
            />
            <figcaption>This information about this thing</figcaption>
          </figure>
          <figure>
            <img
              src="https://res.cloudinary.com/labofthingsimages/image/upload/v1670295149/Portfolio_Images/Screen_Shot_2018-12-27_at_8.38.31_PM_dgf8lv.png"
              alt="Buttercups"
            />
            <figcaption>This information about this thing</figcaption>
          </figure>
        </ProjectWrapper>
      </main>
      <Button>Dark</Button>
      <Button>Light</Button>
    </div>
  );
}
