import Head from 'next/head';
import styled from 'styled-components';
import ButtonSlider from '../components/ButtonSlider';

const ProjectWrapper = styled.section`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(25rem, 1fr));
`;

const Wrapper = styled.div`
  padding: 3rem;
`;

export default function Home() {
  const tabs = [{ name: 'tab' }, { name: 'tab' }, { name: 'tab' }];

  return (
    <Wrapper>
      <Head>
        <title>Joyanna's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProjectWrapper></ProjectWrapper>
      </main>
      <ButtonSlider tabs={tabs}></ButtonSlider>
    </Wrapper>
  );
}
