import Head from "next/head";
import styled from "styled-components";
import { useState, useMemo } from "react";
import ProjectShelf from "../components/ProjectShelf";
import PortfolioFilter from "../components/PortfolioFilter";
import YearTimeline from "../components/YearTimeline";
import Navigation from "../components/Navigation";
import { portfolioProjects } from "../data/portfolioData";

const Wrapper = styled.main`
  transition: all 0.3s ease-in-out;
  background: var(--bg);
  color: var(--text);
  h1 {
    margin-bottom: 0.5rem;
    font-family: loos-extrawide, sans-serif;
  }
`;

const Intro = styled.header`
  padding: 5rem 0.5rem 2rem;
  text-align: center;
`;

const PortfolioSection = styled.section`
  padding: 1rem 0.5rem;
  background: var(--gradient);
  /* backdrop-filter: saturate(180%) blur(10px); */

  @media (min-width: 768px) {
    padding: 2rem 3rem;
  }

  h2 {
    font-size: 2rem;
  }
`;

export default function Home() {
  const [selectedTags, setSelectedTags] = useState([]);
  const [selectedYears, setSelectedYears] = useState([]);

  // Use centralized portfolio data
  const allPortfolioItems = useMemo(() => {
    return portfolioProjects;
  }, []);

  // Extract unique tags (normalize case)
  const uniqueTags = useMemo(() => {
    const tagSet = new Set();
    allPortfolioItems.forEach((item) => {
      item.tag.forEach((tag) => {
        // Normalize tag capitalization
        tagSet.add(tag.charAt(0).toUpperCase() + tag.slice(1).toLowerCase());
      });
    });
    return Array.from(tagSet).sort();
  }, [allPortfolioItems]);

  // Extract unique years
  const uniqueYears = useMemo(() => {
    const yearSet = new Set();
    allPortfolioItems.forEach((item) => {
      if (item.date) {
        // Extract year from date string
        const year = item.date.toString().substring(0, 4);
        yearSet.add(year);
      }
    });
    return Array.from(yearSet).sort((a, b) => parseInt(a) - parseInt(b));
  }, [allPortfolioItems]);

  // Split portfolio items into matched and unmatched (AND logic)
  const { matchedItems, unmatchedItems } = useMemo(() => {
    // If no filters selected, show all items
    if (selectedTags.length === 0 && selectedYears.length === 0) {
      return { matchedItems: allPortfolioItems, unmatchedItems: [] };
    }

    const matched = [];
    const unmatched = [];

    allPortfolioItems.forEach((item) => {
      // Check tag matching (if any tags selected)
      let matchesTags =
        selectedTags.length === 0 ||
        item.tag.some((tag) => {
          const normalizedTag =
            tag.charAt(0).toUpperCase() + tag.slice(1).toLowerCase();
          return selectedTags.includes(normalizedTag);
        });

      // Check year matching (if any years selected)
      let matchesYears = selectedYears.length === 0;
      if (selectedYears.length > 0 && item.date) {
        const itemYear = item.date.toString().substring(0, 4);
        matchesYears = selectedYears.includes(itemYear);
      }

      // AND logic: item must match both filters
      if (matchesTags && matchesYears) {
        matched.push(item);
      } else {
        unmatched.push(item);
      }
    });

    return { matchedItems: matched, unmatchedItems: unmatched };
  }, [allPortfolioItems, selectedTags, selectedYears]);

  const handleTagToggle = (tag) => {
    setSelectedTags((prev) => (prev.includes(tag) ? [] : [tag]));
  };

  const handleYearToggle = (year) => {
    setSelectedYears((prev) =>
      prev.includes(year) ? prev.filter((y) => y !== year) : [...prev, year]
    );
  };

  const handleClearYearFilters = () => {
    setSelectedYears([]);
  };

  const handleClearFilters = () => {
    setSelectedTags([]);
    setSelectedYears([]);
  };

  return (
    // <Providers>
    <Wrapper>
      <Head>
        <title>Joyanna's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/kim6tqe.css"
        ></link>
      </Head>
      <Navigation showBackButton={false} />
      <main>
        <Intro>
          <h1>Welcome...</h1>
          <h2>Test site for all of my work</h2>
        </Intro>

        <PortfolioFilter
          tags={uniqueTags}
          selectedTags={selectedTags}
          onTagToggle={handleTagToggle}
          onClearFilters={handleClearFilters}
        />

        <YearTimeline
          years={uniqueYears}
          selectedYears={selectedYears}
          onYearToggle={handleYearToggle}
          onClearFilters={handleClearYearFilters}
        />

        {selectedTags.length === 0 && selectedYears.length === 0 ? (
          <PortfolioSection>
            <h2>All Projects</h2>
            <ProjectShelf imgs={allPortfolioItems} />
          </PortfolioSection>
        ) : (
          <>
            <PortfolioSection>
              <h2>
                {selectedTags.length > 0 && `Tags: ${selectedTags.join(", ")}`}
                {selectedTags.length > 0 && selectedYears.length > 0 && " | "}
                {selectedYears.length > 0 &&
                  `Years: ${selectedYears.join(", ")}`}
              </h2>
              <ProjectShelf imgs={matchedItems} />
            </PortfolioSection>

            {unmatchedItems.length > 0 && (
              <PortfolioSection>
                <h2>Other Projects</h2>
                <ProjectShelf imgs={unmatchedItems} />
              </PortfolioSection>
            )}
          </>
        )}
      </main>
    </Wrapper>
    // </Providers>
  );
}
