const ProductDesign = [
  // {
  //   title: 'Membership Calculator',
  //   description: 'Branding for a gym in Mexico near the beach',
  //   date: '2023',
  //   alt: 'alt',
  //   tag: ['Development', 'Marketing', 'UX/UI'],
  //   path: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1668615393/20210409_194223_wmcoo3.jpg',
  //   src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1678985956/Portfolio_Images/Screen_Shot_2023-03-16_at_12.59.02_PM_bte7b0.png',
  // },
  {
    title: 'Seats First Booking Test',
    description: 'User Test showing that seats first is the best option',
    date: '2023',
    alt: 'alt',
    tag: ['App', 'Testing', 'Research'],
    path: '/portfolio/SeatsFirst',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1678985748/Portfolio_Images/Screen_Shot_2023-03-16_at_12.55.38_PM_t43csq.png',
  },
  {
    title: 'Regal Theatre Pages',
    description: 'Adding meaningful information to the Theatre Pages',
    date: '2023',
    alt: 'alt',
    tag: ['Website', 'Development'],
    path: '/portfolio/RegalTheatrePages',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1678985861/Portfolio_Images/Screen_Shot_2023-03-16_at_12.57.26_PM_q6my6b.png',
  },
  {
    title: 'Regal Movie Pages',
    description: 'Removing the scroll time from the movie pages',
    date: '2022',
    alt: 'alt',
    tag: ['Website', 'Development'],
    path: '/portfolio/RegalMoviePages',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1678985500/Portfolio_Images/Screen_Shot_2023-03-16_at_12.51.29_PM_rpfrx2.png',
  },
  // {
  //   title: 'UI Theme',
  //   description: 'Branding for a gym in Mexico near the beach',
  //   date: '2022',
  //   alt: 'alt',
  //   tag: ['Website', 'Development'],
  //   path: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1668615393/20210409_194223_wmcoo3.jpg',
  //   src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1678986478/Portfolio_Images/Screen_Shot_2023-03-16_at_1.07.46_PM_hqfs6g.png',
  // },
  {
    title: 'Competative Analysis & Assesment',
    description: 'Comparing the Regal App to the Competators',
    date: '2021',
    alt: 'alt',
    tag: ['App', 'Research'],
    path: 'portfolio/CompetativeAnalysis',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1678986805/Portfolio_Images/Screen_Shot_2023-03-16_at_1.10.43_PM_vjp7qw.png',
  },
  {
    title: 'Cadre5 Website',
    description: 'Branding for a gym in Mexico near the beach',
    date: '2021',
    alt: 'alt',
    tag: ['Website', 'Development'],
    path: '/portfolio/Cadre5',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1678820158/Portfolio_Images/Screen_Shot_2022-02-22_at_9.22.13_AM_zszmji.png',
  },
  {
    title: 'Seat Maps',
    description: 'Branding for a gym in Mexico near the beach',
    date: '2020',
    alt: 'alt',
    tag: ['Website', 'UI/UX'],
    path: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1668615393/20210409_194223_wmcoo3.jpg',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1670295122/Portfolio_Images/Screen_Shot_2020-03-23_at_11.21.55_AM_rcbflw.png',
  },
  {
    title: 'Marketing Consent',
    description: 'Branding for a gym in Mexico near the beach',
    date: '2019',
    alt: 'alt',
    tag: ['Website', 'UI/UX'],
    path: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1668615393/20210409_194223_wmcoo3.jpg',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1670295125/Portfolio_Images/Screen_Shot_2020-03-19_at_4.54.33_PM_vfn9qv.png',
  },
  {
    title: 'Fillauer',
    description: 'Branding for a gym in Mexico near the beach',
    date: '2018',
    alt: 'alt',
    tag: ['Website', 'UI/UX'],
    path: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1668615393/20210409_194223_wmcoo3.jpg',
    src: 'https://res.cloudinary.com/labofthingsimages/image/upload/v1670295133/Portfolio_Images/Artboard_fqh6kw.png',
  },
];

export default ProductDesign;
